istio-proxyv2: add v1.31 (#99772)
* istio-proxyv2: add v1.31

* istio-proxyv2: update tracking statements

[dhi-commit=8d708a2796eea717964d46908b6381308f0dfc58]

diff --git a/image/istio-proxyv2/debian-13/1.31.yaml b/image/istio-proxyv2/debian-13/1.31.yaml
--- a/image/istio-proxyv2/debian-13/1.31.yaml
+++ b/image/istio-proxyv2/debian-13/1.31.yaml
@@ -4,26 +4,30 @@ name: istio-proxyv2 1.x
 image: dhi.io/istio-proxyv2
 variant: runtime
 tags:
-  - "1.30"
-  - 1.30.4
-  - 1.30-debian
-  - 1.30-debian13
-  - 1.30.4-debian
-  - 1.30.4-debian13
+  - "1"
+  - "1.31"
+  - 1.31.0
+  - 1-debian
+  - 1-debian13
+  - 1.31-debian
+  - 1.31-debian13
+  - 1.31.0-debian
+  - 1.31.0-debian13
 platforms:
   - linux/amd64
   - linux/arm64
 dates:
-  release: "2026-05-18"
+  release: "2026-08-31"
+  end-of-life: "2027-02-28"
 vars:
   BAZEL_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "arm64" }'
-  BAZEL_VERSION: 7.7.1
-  COMMIT_SHA: 4220640be99e4cad69652d9eb2010bc5257f6a8e
-  ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
-  SEMVER_MAJOR_MINOR_VERSION: "1.30"
+  BAZEL_VERSION: 8.7.0
+  COMMIT_SHA: eed52ebb66ade45214088877b0f82855d954060d
+  ISTIO_PROXY_SHA: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
+  SEMVER_MAJOR_MINOR_VERSION: "1.31"
   SEMVER_MAJOR_VERSION: "1"
-  SEMVER_VERSION: 1.30.4
-  VERSION: 1.30.4
+  SEMVER_VERSION: 1.31.0
+  VERSION: 1.31.0
 contents:
   repositories:
     - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
@@ -77,32 +81,32 @@ contents:
           - findutils
           - gawk
         files:
-          - url: git+https://github.com/istio/istio.git#1.30.4
-            checksum: 4220640be99e4cad69652d9eb2010bc5257f6a8e
+          - url: git+https://github.com/istio/istio.git#1.31.0
+            checksum: eed52ebb66ade45214088877b0f82855d954060d
             path: /go/src/istio.io/istio
             spdx:
               name: istio
-              version: 1.30.4
+              version: 1.31.0
               packages:
                 - name: istio
-                  purl: pkg:golang/istio.io/istio@1.30.4
+                  purl: pkg:golang/istio.io/istio@1.31.0
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: git+https://github.com/istio/proxy.git#1.30.4
-            checksum: ce177c56fe75661f16b654e2f164d4ab02058222
+          - url: git+https://github.com/istio/proxy.git#1.31.0
+            checksum: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
             path: ${source.dir}/istio-proxy
             spdx:
               name: istio-proxy
-              version: 1.30.4
+              version: 1.31.0
               packages:
                 - name: istio-proxy
-                  purl: pkg:golang/github.com/istio/proxy@1.30.4
+                  purl: pkg:golang/github.com/istio/proxy@1.31.0
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: https://github.com/bazelbuild/bazel/releases/download/7.7.1/bazel-7.7.1-linux-${BAZEL_ARCH}
-            checksum: https://github.com/bazelbuild/bazel/releases/download/7.7.1/bazel-7.7.1-linux-${BAZEL_ARCH}.sha256
+          - url: https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-linux-${BAZEL_ARCH}
+            checksum: https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-linux-${BAZEL_ARCH}.sha256
             path: /opt/bazel/bin/bazel
             uid: 0
             gid: 0
@@ -115,8 +119,8 @@ contents:
             # Extract proxy SHA from istio.deps and validate against tracking
             proxy_sha=$(jq -r '.[] | select(.name == "PROXY_REPO_SHA") | .lastStableSHA' "/go/src/istio.io/istio/istio.deps")
 
-            if [ "$proxy_sha" != 'ce177c56fe75661f16b654e2f164d4ab02058222' ]; then
-              echo "ERROR: ISTIO_PROXY_SHA mismatch: ce177c56fe75661f16b654e2f164d4ab02058222 (def) / $proxy_sha (istio.deps)" >&2
+            if [ "$proxy_sha" != '0a12a02f0db52f6d229ec0fbe0f2091e1c02098b' ]; then
+              echo "ERROR: ISTIO_PROXY_SHA mismatch: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b (def) / $proxy_sha (istio.deps)" >&2
               exit 1
             fi
         - name: update go dependencies
@@ -377,7 +381,7 @@ contents:
             # Configure FIPS BoringSSL if requested
             BORINGSSL_FLAGS=()
             if [ '${target.fips}' = true ]; then
-              case '1.30' in
+              case '1.31' in
                 1.30 | 1.31) BORINGSSL_FLAGS+=(--config=boringssl-fips) ;;
                 *) BORINGSSL_FLAGS+=(--define=boringssl=fips) ;;
               esac
@@ -445,16 +449,16 @@ contents:
               --override_repository=intel_dlb=/src/dlb-stub
               --@envoy//contrib/dlb/source:enabled=false
             "
-            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.30.4 > /opt/docker/sbom/envoy/.spdx.envoy.json
+            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.31.0 > /opt/docker/sbom/envoy/.spdx.envoy.json
         - name: build-pilot-agent
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.30.4
-                       -X istio.io/istio/pkg/version.buildGitRevision=4220640be99e4cad69652d9eb2010bc5257f6a8e
+            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.31.0
+                       -X istio.io/istio/pkg/version.buildGitRevision=eed52ebb66ade45214088877b0f82855d954060d
                        -X istio.io/istio/pkg/version.buildStatus=Clean
-                       -X istio.io/istio/pkg/version.buildTag=1.30.4
+                       -X istio.io/istio/pkg/version.buildTag=1.31.0
                        -X istio.io/istio/pkg/version.buildHub=docker.io/dhi
                        -X istio.io/istio/pkg/version.buildOS=$(go env GOOS)
                        -X istio.io/istio/pkg/version.buildArch=$(go env GOARCH)"
@@ -522,7 +526,7 @@ os-release:
   home-url: https://docker.com/products/hardened-images/
   bug-report-url: https://docker.com/support/
 environment:
-  ISTIO_META_ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
+  ISTIO_META_ISTIO_PROXY_SHA: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
 paths:
   - type: symlink
     path: /usr/sbin/iptables
